/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout copy/index` | `/workout copy/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout copy/workout/index` | `/workout copy/workout/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routine/index` | `/routine/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines/index` | `/routines/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines copy/index` | `/routines copy/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises/index` | `/exercises/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines copy 2/index` | `/routines copy 2/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/index` | `/profile/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history/index` | `/history/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workout copy/index` | `/workout copy/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workout copy/workout/index` | `/workout copy/workout/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/routine/index` | `/routine/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/routines/index` | `/routines/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/routines copy/index` | `/routines copy/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exercises/index` | `/exercises/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/routines copy 2/index` | `/routines copy 2/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/index` | `/profile/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history/index` | `/history/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workout copy/index${`?${string}` | `#${string}` | ''}` | `/workout copy/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workout copy/workout/index${`?${string}` | `#${string}` | ''}` | `/workout copy/workout/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/routine/index${`?${string}` | `#${string}` | ''}` | `/routine/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/routines/index${`?${string}` | `#${string}` | ''}` | `/routines/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/routines copy/index${`?${string}` | `#${string}` | ''}` | `/routines copy/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exercises/index${`?${string}` | `#${string}` | ''}` | `/exercises/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/routines copy 2/index${`?${string}` | `#${string}` | ''}` | `/routines copy 2/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/index${`?${string}` | `#${string}` | ''}` | `/profile/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history/index${`?${string}` | `#${string}` | ''}` | `/history/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workout${`?${string}` | `#${string}` | ''}` | `/workout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout copy/index` | `/workout copy/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout copy/workout/index` | `/workout copy/workout/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routine/index` | `/routine/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines/index` | `/routines/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines copy/index` | `/routines copy/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises/index` | `/exercises/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines copy 2/index` | `/routines copy 2/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/index` | `/profile/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history/index` | `/history/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
